name: hcnmn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.9.0
  - torchvision
  - cudatoolkit=11.3  # Adjust based on your CUDA version
  - numpy
  - scipy
  - h5py
  - tqdm
  - ipython
  - matplotlib
  - nltk
  - scikit-learn
  - pandas
  - pillow
  - pip
  - pip:
    - conceptnet-lite
    - wikitextparser